### ISSUE TITLE
WRAP Up 1

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/wrap-up#1]
### Agenda
 - Some github tricks: using "resolves" in PR's can close issues, etc. (1 min)
 - How to set up a templates to use for tickets (5 mins)
 - How to actively design code instead of doing it on the fly. A lot of this is based on the idea of using code to manage complexity (5-10 mins)
 - Catalina drawing things in Rmd (DiagrammeR) (5 mins?)

**Comment by remi-daigle** [comment]
Fun! DiagrammeR! I used that once a long time ago for the Software Carpentry dplyr and tidyr lessons! See: 
- some of the [code](https://github.com/swcarpentry/r-novice-gapminder/blob/main/fig/13-dplyr-generate-figures.R)
- some of the [output](https://swcarpentry.github.io/r-novice-gapminder/13-dplyr/index.html)
